import {afterEach,describe,it,expect,vi} from 'vitest';
import {createHash} from 'node:crypto';
import {defaultProjectSources,SOURCE_WALLETS} from '@meme/domain';
import {feedCandidates,walletBuys,ProjectDiscovery,SWAP_PROGRAMS} from './project-discovery.js';
import {acceptsDiscovery} from './live-service.js';
function encoded(data:Buffer){let n=BigInt('0x'+data.toString('hex')),result='';const chars='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';while(n){result=chars[Number(n%58n)]+result;n/=58n;}return result;}
const wallet=SOURCE_WALLETS[0],ca=SOURCE_WALLETS[1];
function transaction(name='buy',program=Object.keys(SWAP_PROGRAMS)[0]){return {blockTime:1791600000,transaction:{message:{accountKeys:[{pubkey:wallet,signer:true},{pubkey:'token-account'}],instructions:[{programId:program,data:encoded(createHash('sha256').update(`global:${name}`).digest().subarray(0,8)),accounts:[wallet,'token-account']}]}},meta:{err:null,fee:5000,preBalances:[1000000000],postBalances:[899995000],preTokenBalances:[],postTokenBalances:[{owner:wallet,mint:ca,accountIndex:1,uiTokenAmount:{amount:'999999999999999999'}}]}};}
afterEach(()=>{vi.useRealTimers();vi.unstubAllEnvs();});
describe('wallet buy classification',()=>{
 it('recognizes confirmed Pump buys without floating point token rounding',()=>expect(walletBuys(transaction(),wallet)).toEqual([ca]));
 it('rejects transfers, airdrops, failed tx, LP and unknown programs',()=>{for(const tx of [transaction('transfer'),transaction('deposit'),transaction('buy','unknown')])expect(walletBuys(tx,wallet)).toEqual([]);const tx=transaction();tx.meta.err='failed' as any;expect(walletBuys(tx,wallet)).toEqual([]);tx.meta.err=null;tx.transaction.message.accountKeys[0].signer=false;expect(walletBuys(tx,wallet)).toEqual([]);});
 it('accepts token-to-token swaps even without net SOL spend',()=>{const tx=transaction('route','JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4');tx.meta.postBalances=[1000000000];tx.meta.preTokenBalances=[{owner:wallet,mint:'sold-token',accountIndex:2,uiTokenAmount:{amount:'100'}}] as any;expect(walletBuys(tx,wallet)).toEqual([ca]);});
 it('does not treat unrelated token gains as swap output',()=>{const tx=transaction();tx.transaction.message.instructions[0].accounts=[wallet];expect(walletBuys(tx,wallet)).toEqual([]);});
 it('requires both task start and source enable time for wallet events',()=>{const c=defaultProjectSources();c.wallet.enabled=true;const run={started_at:new Date(1000),source_activated_at:{wallet:2000},project_sources:c};const s:any={provider:'wallet',time:4000,identity:{transactionTime:2000}};expect(acceptsDiscovery(run,s)).toBe(false);s.identity.transactionTime=2001;expect(acceptsDiscovery(run,s)).toBe(true);s.time=2000;expect(acceptsDiscovery(run,s)).toBe(false);});
});
describe('shared feed',()=>{
 it('uses token creation time, not migration/createTime, and preserves missing fields',()=>{const c=feedCandidates([{tokenAddress:ca,createTime:10,tokenCreateTime:20,marketCapUSD:50000,kolNum:0,dexId:'pfamm'}],100)[0];expect(c.facts).toMatchObject({createdAt:20,kol:0});expect(c.time).toBe(100);expect(feedCandidates([{tokenAddress:'invalid'}],100)).toEqual([]);});
 it('polls once globally each ten seconds and never overlaps',async()=>{
  vi.useFakeTimers();vi.stubEnv('XXYY_API_KEY','test-key');const c=defaultProjectSources();c.xxyy.enabled=true;c.memeinfo.enabled=false;
  const db:any={query:vi.fn(async()=>({rows:[]}))};const deliver=vi.fn(async()=>{}),request=vi.fn(async()=>({ok:true,json:async()=>({code:200,data:{items:[]}})}));
  const d=new ProjectDiscovery(db,deliver,request as any);d.update([{chain:'sol',project_sources:c},{chain:'sol',project_sources:c}]);await vi.advanceTimersByTimeAsync(1);expect(request).toHaveBeenCalledTimes(1);await vi.advanceTimersByTimeAsync(9998);expect(request).toHaveBeenCalledTimes(1);await vi.advanceTimersByTimeAsync(1);expect(request).toHaveBeenCalledTimes(2);d.close();await vi.advanceTimersByTimeAsync(10000);expect(request).toHaveBeenCalledTimes(2);
 });
 it('continues other candidates when one lookup fails',async()=>{vi.stubEnv('XXYY_API_KEY','test-key');const c=defaultProjectSources();c.xxyy.enabled=true;const request=vi.fn(async()=>({ok:true,json:async()=>({code:200,data:{items:[{tokenAddress:ca},{tokenAddress:wallet}]}})}));const deliver=vi.fn().mockRejectedValueOnce(new Error('lookup')).mockResolvedValue(undefined);const d:any=new ProjectDiscovery({} as any,deliver,request as any);d.runs=[{chain:'sol',project_sources:c}];await d.pollFeed();expect(deliver).toHaveBeenCalledTimes(2);expect(d.status.xxyy.error).toContain('1 个');});
 it('keeps a temporarily unavailable wallet transaction in the saved page and checks the other wallet',async()=>{const c=defaultProjectSources();c.wallet.enabled=true;const state={since:1,pending:[{signature:'s'}],finished:true,target:'s'};const db={query:vi.fn(async()=>({rows:[{state_json:state}]}))};const d:any=new ProjectDiscovery(db as any,vi.fn());d.runs=[{chain:'sol',project_sources:c}];d.rpc=vi.fn(async()=>null);await expect(d.scanWallets()).rejects.toThrow('incomplete');expect(state.pending).toHaveLength(1);expect(db.query).toHaveBeenCalledTimes(2);});
 it('isolates inbox failures without marking them consumed',async()=>{const db={query:vi.fn().mockResolvedValueOnce({rows:[{event_key:'1',provider:'wallet',payload:{}},{event_key:'2',provider:'wallet',payload:{}}]}).mockResolvedValue({rows:[]})};const d:any=new ProjectDiscovery(db as any,vi.fn().mockRejectedValueOnce(new Error('offline')).mockResolvedValue(undefined));await d.drainInbox();expect(db.query.mock.calls[1][0]).toContain('retry_at');expect(db.query.mock.calls[2][0]).toContain('processed_at=now()');});
});
