ALTER TABLE backtest_trades ADD COLUMN IF NOT EXISTS trade_no integer;
ALTER TABLE backtest_trades ADD COLUMN IF NOT EXISTS first_entry_price numeric;
ALTER TABLE backtest_trades ADD COLUMN IF NOT EXISTS buy_amount numeric;
ALTER TABLE backtest_trades ADD COLUMN IF NOT EXISTS buy_fees numeric;
ALTER TABLE backtest_trades ADD COLUMN IF NOT EXISTS buy_slippage_cost numeric;
ALTER TABLE backtest_trades ADD COLUMN IF NOT EXISTS buy_tax_cost numeric;
ALTER TABLE backtest_signals ADD COLUMN IF NOT EXISTS trade_no integer;
ALTER TABLE backtest_signals ADD COLUMN IF NOT EXISTS event_order integer;
CREATE UNIQUE INDEX IF NOT EXISTS backtest_trade_number ON backtest_trades(run_id,chain,ca,pair_id,trade_no) WHERE trade_no IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS backtest_event_order ON backtest_signals(run_id,chain,ca,pair_id,trade_no,event_order) WHERE trade_no IS NOT NULL AND event_order IS NOT NULL;
COMMENT ON COLUMN backtest_trades.trade_no IS '任务内每池完整交易的稳定编号，从 1 开始；历史不可确定时为空。';
COMMENT ON COLUMN backtest_trades.first_entry_price IS '首次买入的原始价格或市值，不使用加仓后均价替代。';
COMMENT ON COLUMN backtest_trades.buy_amount IS '本笔交易含所有加仓的累计买入金额，不含交易成本。';
COMMENT ON COLUMN backtest_trades.buy_fees IS '首次买入及加仓累计手续费。';
COMMENT ON COLUMN backtest_trades.buy_slippage_cost IS '首次买入及加仓累计滑点成本。';
COMMENT ON COLUMN backtest_trades.buy_tax_cost IS '首次买入及加仓累计买入税。';
COMMENT ON COLUMN backtest_signals.trade_no IS '所属完整交易在该池中的稳定编号，与交易表 trade_no 关联。';
COMMENT ON COLUMN backtest_signals.event_order IS '完整交易内的事件序号，首次买入为 1，加仓递增，卖出为最后一项。';
COMMENT ON COLUMN backtest_trades.exit_reason IS '退出原因：take_profit、stop_loss、profit_lock（动态锁盈）、invalidation、timeout、end_of_backtest。';
